web:
  build: .
  ports:
    - "8080:8080"
  volumes:
    # - .:/code
    - ./OilSecurity/dist/OilSecurity.war:/usr/local/tomcat/webapps/ROOT.war
  links:
    - mysql:localhost
mysql:
  container_name: s_mysql
  image: "mysql:5"
  ports:
    - "3306"
  volumes:
    - ./db:/docker-entrypoint-initdb.d/
  environment:
    - MYSQL_ROOT_PASSWORD=@MMJYBA864qMKsXb
    - MYSQL_DATABASE=oilsec
    - MYSQL_USER=oiluser
    - MYSQL_PASSWORD=oiluser
